### ISSUE TITLE
Oops, error right out of the box

### ISSUE THREAD

**Issue by FlyboyArt** [jondot/version_bumper#1]
I did a gem install version_bump

Added require 'version_bumper' to my rake file

Did rake -T and got...

rake aborted!
no such file to load -- version_bumper
/Users/artlap/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Users/artlap/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
/Users/artlap/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
/Users/artlap/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in`new_constants_in'
/Users/artlap/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
/Users/artlap/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'

**Comment by jondot** [comment]
Are you running on a mac (if not please specify what environment you're using)?
I've noticed you mistyped `vesion_bumper` in your gem install statement. make sure you really have it installed with `gem list -d version_bumper`
Heres a fresh install:

Jon-Dotans-Mac:~ jondotan$ gem install version_bumper
Successfully installed version_bumper-0.1.0
1 gem installed
Installing ri documentation for version_bumper-0.1.0...
Installing RDoc documentation for version_bumper-0.1.0...
Jon-Dotans-Mac:~ jondotan$ mate Rakefile
Jon-Dotans-Mac:~ jondotan$ rake -T
(in /Users/jondotan)
rake bump:build     # bump build
rake bump:init      # create a blank version file
rake bump:major     # bump major
rake bump:minor     # bump minor
rake bump:revision  # bump revision
Jon-Dotans-Mac:~ jondotan$

**Comment by FlyboyArt** [comment]
Yes, a Mac and yes a typo in this report but not at the keyboard during the install . Everything went as it did on yours except for the error message I get.

-Art

**Comment by jondot** [comment]
Just noticed you're trying to add to a rails rakefile.
did you make sure you have 

gem 'version_bumper'

in your Gemfile ?

**Comment by FlyboyArt** [comment]
Nope... thought if it was just Rake using it, it wasn't needed in the GemFile. Am I wrong??

**Comment by jondot** [comment]
No, you should add it to the Gemfile

**Comment by FlyboyArt** [comment]
Thanks. Works now... sorry about not understanding this better...

**Comment by jondot** [comment]
sure. will add a note to readme.
