### ISSUE TITLE
Does this autoincrement versions?

### ISSUE THREAD

**Issue by shawnmclean** [jondot/version_bumper#3]
I'm new to setting up versioning for my projects. Does it auto-increment the values or do I have to edit the file manually every time I change something? Could you help me get versions setup in my project please?

My project is located at: https://github.com/Mixmasterxp/SimpleCrypto.net

**Comment by jondot** [comment]
Hey there!
Yes it should increment versions for you, by level of your choosing:

```
    $ rake -T
    rake bump:build     # bump build
    rake bump:init      # write a blank version
    rake bump:major     # bump major
    rake bump:minor     # bump minor
    rake bump:revision  # bump revision


    $ rake bump:init
    version: 0.0.0.0
    $ rake bump:revision
    version: 0.0.1.0
    $ rake bump:major
    version: 1.0.0.0
```

Does this help?
