### ISSUE TITLE
"undefined method `succ' for nil:NilClass"

### ISSUE THREAD

**Issue by jchannon** [jondot/version_bumper#4]
In version.rb I think you need to do this on line 25:

`version = @v[part] = @v[part].to_i.succ`

**Comment by jondot** [comment]
Hi there,
`#succ` was used because it should do "the right thing", with numbers - it will take a next number and with letters it should take the next letter, example:  

```
"21".succ
=> "22"
"a".succ
=> "b"
```

I think the `nil` error might be because `@v[part]` itself doesn't exist in your case.

**Comment by jchannon** [comment]
I was calling it like so:

def env_buildversion
  bumper_version.to_s
end

task :currentversion do
   bumper_version.bump_build
   bumper_version.write('VERSION')
   puts env_buildversion
end

**Comment by jondot** [comment]
OK, and how does a sample of your version look like?

**Comment by jchannon** [comment]
I've uninstalled and reinstalled the gem and my sample code above works
fine now.

Odd!

Thanks

**Comment by jondot** [comment]
Happy it works :)
Feel free to close this issue once you feel comfortable that the issue is resolved :+1:

**Comment by jchannon** [comment]
Thanks for the help!

**Comment by jchannon** [comment]
I've just installed to a prod server and get the same error:(

**Comment by jondot** [comment]
That's strange. From what you're said before, if you'll install again, it will be resolved?
Sounds like a network cache / CDN problem? are you under any kind of corporate / internal caching proxy?

How about doing a `gem list -d version_bumper` and taking note of what exactly is installed right now, and then do the same thing you did to resolve earlier, and run `gem list -d version_bumper` again to see what's changed.

**Comment by jchannon** [comment]
All fixed, permissions and wrong version format! Thanks

**Comment by jondot** [comment]
OK so if it's a permission problem that relates to your server's setup. When are you getting that? can you paste a terminal output?

**Comment by jchannon** [comment]
Are you about for a chat on Jabbr.net?

**Comment by jondot** [comment]
not familiar with it, feel free to email me at dotan@paracode.com

**Comment by jchannon** [comment]
its a oss chat room. I'm running rake via Team City and its complaining that it cant find VERSION. I'm guessing this is a relative path issue
